name: tfcheck
on: [pull_request]
jobs:
  tffmtvalidate:
    name: terraform check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -recursive -check
        continue-on-error: false
